// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okjvfhvrxjhubskncjng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ranZmaHZyeGpodWJza25jam5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTQ3MTMsImV4cCI6MjA2MzEzMDcxM30.mvQVY2kd2XJslmzKyLJi8R3cpWuKHXUW0r2sdE8eg5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);